name: ci-cd-taller

on: 
  push:
    branches: ['main']

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    -name: Checkout code
      uses: actions/checkout@v3

    -name: verificar Archivos
      run: |
        if [ -f vistas/index.html ] && [ -f CSS/styles.css ]; then
          echo "Los archivos index.html y styles.css existen."
        else
          echo "Error: Uno o ambos archivos no existen."
          exit 1
        fi

  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      -name: Simulacion de despliegue
      run: echo "Simulando despliegue..."